### ISSUE TITLE
configure.sh não confere módulo soundex

### ISSUE THREAD

**Issue by staticdev** [avanco/UGCNormal#1]
Ao rodar o normalizador recebo o erro:

![index](https://user-images.githubusercontent.com/1446633/35167800-e8d41b80-fd3d-11e7-9115-2f6e7c0b7f48.jpeg)

**Comment by avanco** [comment]
olá Thiago,

tente mudar em spell.pl o caminho que o speller utiliza:
```
# use lib => for pre-processing UGCNormal module
#use lib "$ENV{HOME}/ugc_norm/speller";
# use lib => run Speller
use lib ".";
```

**Comment by staticdev** [comment]
Desculpe minha ignorância em Perl.
Não seria um cpanp -i Text::Soundex ? Fiz isso para o Text::LevenshteinXS e Parallel::Loops.

**Comment by staticdev** [comment]
É um módulo interno né?

**Comment by avanco** [comment]
sim, isso, é um módulo interno
veja se funciona mudando para `use lib ".";`

**Comment by carolcoimbra** [comment]
Parece que mudando para use lib "."; funciona. Mas aparecem novos erros.
![image](https://user-images.githubusercontent.com/11412595/35169948-9bd426a6-fd45-11e7-9ace-0d540a5f6145.png)

**Comment by avanco** [comment]
o caminho para resources não deve estar ok

Tente forçar o path completo para testar.
Tente tirar essa var de ambiente nas seguintes linhas de spell.pl e colocar o path completo
```
   352	    $siglas_lexicon_file = "$ENV{PWD}/resources/lexico_siglas.txt";
   353	    $int_lexicon_file = "$ENV{PWD}/resources/lexico_internetes.txt";
   354	    $int_sigl_lexicon_file = "$ENV{PWD}/resources/lexico_internetes_sigl_abrv.txt";
   355	    $np_lexicon_file = "$ENV{PWD}/resources/lexico_nome_proprio.txt";
   356	    $estr_lexicon_file = "$ENV{PWD}/resources/lexico_estrangeirismo.txt";
   357	    $medidas_lexicon_file = "$ENV{PWD}/resources/lexico_unidade_medida.txt";
   428	    $blacklist = "$ENV{PWD}/resources/blacklist_gemeas.txt";
```

**Comment by staticdev** [comment]
Fiz uma versão que já configura tudo no docker: https://github.com/staticdev/ugcnormal-microservice. Acho que podemos fechar esse issue.
